### ISSUE TITLE
Uncaught exception mopidy-radio-de

### ISSUE THREAD

**Issue by a2dx** [hechtus/mopidy-radio-de#11]
Hello i have installed sucessfully mopidy-radio-de but when i start mopidy there ist an error

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 272, in run
    backends = self.start_backends(config, backend_classes, audio)
  File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 343, in start_backends
    config=config, audio=audio).proxy()
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 93, in start
    obj = cls(_args, *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_radio_de/actor.py", line 48, in **init**
    proxy=proxy)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_radio_de/api.py", line 57, in **init**
    if len(proxy):
TypeError: object of type 'NoneType' has no len()

It seems to be a problem about proxy configuration maybe?
Anybody has an idea what could i do? Thx for help

**Comment by paulhandy** [comment]
I second this. It seems broken

**Comment by vasyugan** [comment]
Yes, extension is broken. 
Immediately after installation, mopidyctl config says:

[radio-de]
enabled = false  ; Extension disabled due to config errors.
language =   ; Must be set.
favorites =

**Comment by Mebus** [comment]
I have got the same problem:

<code>
2015-06-28 12:26:17,289 ERROR [10848:MainThread] mopidy.commands: Uncaught exception Traceback (most recent call last): File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 274, in run backends = self.start_backends(config, backend_classes, audio) File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 352, in start_backends config=config, audio=audio).proxy() File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 93, in start obj = cls(args, *kwargs) File "/usr/local/lib/python2.7/dist-packages/mopidy_radio_de/actor.py", line 48, in init proxy=proxy) File "/usr/local/lib/python2.7/dist-packages/mopidy_radio_de/api.py", line 57, in init if len(proxy): TypeError: object of type 'NoneType' has no len() 2015-06-28 12:26:17,300 INFO [10848:MainThread] mopidy.commands: Stopping Mopidy frontends 2015-06-28 12:26:17,305 INFO [10848:MainThread] mopidy.commands: Stopping Mopidy core 2015-06-28 12:26:17,308 INFO [10848:MainThread] mopidy.commands: Stopping Mopidy backends
</code>

<code>
if len(proxy): TypeError: object of type 'NoneType' has no len()
</code>

Looks as if it wasn't a big deal.

Mebus

**Comment by Mebus** [comment]
Please merge paulhandy's pull request!
