### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by lobsn87** [hechtus/mopidy-radio-de#15]
Hey,

i take the configuration like given on GitHub, but this happens:

INFO Starting Mopidy backends: RadioDeBackend, StreamBackend, M3UBackend, FileBackend, SpotifyBackend, SpotifyTunigoBackend
ERROR Got un-handled exception from RadioDeBackend
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 237, in actorerror_handling
yield
File "/usr/lib/python2.7/dist-packages/mopidy/commands.py", line 385, in start_backends
config=config, audio=audio).proxy()
File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 94, in start
obj = cls(*args, **kwargs)
File "/usr/local/lib/python2.7/dist-packages/mopidy_radio_de/actor.py", line 48, in init
proxy=proxy)
File "/usr/local/lib/python2.7/dist-packages/mopidy_radio_de/api.py", line 57, in init
if len(proxy):
TypeError: object of type 'NoneType' has no len()

My Configuration:
[radio-de]
enabled = true
language = german
favorites = Tagesschau, NDR 2, NDR Kultur

How you configured your extension Radio-De???

**Comment by ViperEclipse** [comment]
if think this will solve the issue:
https://discuss.mopidy.com/t/backend-extensions-mopidy-radio-de/1425/4

**Comment by tremebundo** [comment]
Have you the extension working?
